"""F1: the frozen China calibration assets embed the corrected NBS timing.

The January-February NBS release is combined: January is structurally blank in
the corrected panel and February carries the combined figure at its true
mid-March release date. The frozen ladder/horizon/tilt assets were originally
generated under the OLD rule (February copied into January before masking), so
their historical information sets saw the combined release about a month early.

These tests fail against the old assets and pass once the assets are
regenerated by the tracked producer (``pipeline/lib/china_assets.py``):

1. engine-level: at a pre-release origin, the information set contains neither
   a January nor a February observation of a combined-release column;
2. asset-level: frozen ladder rows at exactly those origins reproduce from the
   corrected panel (the old asset rows embed the leaked cell and differ);
3. provenance: the calibration manifest names the tracked producer and the
   panel rule for every China asset.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

REPO = Path(__file__).resolve().parents[1]

if not (REPO / "input").exists():
    pytest.skip("private data layer absent (public clone)", allow_module_level=True)

from pipeline.lib.calibration_assets import ROOT, ASSETS  # noqa: E402

if not (ROOT / ASSETS["china_ladder_full"]).exists():
    pytest.skip("calibration binaries not present", allow_module_level=True)

# Q1 reference quarters with a stable NBS history (old enough that snapshot
# revisions since generation are unlikely), probed at origins after the OLD
# leaky January release (~Feb 15) but before the TRUE combined release
# (~Mar 15): exactly the window where the two rules disagree.
PROBES = [("2018-03-01", "2018-03-05"), ("2019-03-01", "2019-03-07"),
          ("2023-03-01", "2023-03-02")]
COMBINED_COLS = ["ip_cum_yoy", "retail_sales_yoy", "electricity_output_yoy"]


def _info_at(origin, ref_stamp):
    from MIDAS.realtime import RealtimeEngine
    from targets import china as tgt

    _, _, panel = tgt.load_panel()
    return panel, RealtimeEngine(panel).information_set(
        pd.Timestamp(origin), tgt.TARGET, target_period=pd.Timestamp(ref_stamp))


def test_pre_release_origin_sees_no_january_or_february_cell():
    for ref, origin in PROBES:
        year = pd.Timestamp(ref).year
        _, info = _info_at(origin, ref)
        m = info.monthly
        for col in COMBINED_COLS:
            jan, feb = pd.Timestamp(year, 1, 1), pd.Timestamp(year, 2, 1)
            vals = m.loc[m.index.isin([jan, feb]), col]
            assert vals.isna().all(), (
                f"{col}: a Jan/Feb {year} value is visible at {origin}, before "
                "the true combined release date")


def test_frozen_ladder_rows_reproduce_from_the_corrected_panel():
    from pipeline.lib import modelset
    from pipeline.lib.calibration_assets import asset_path
    from pipeline.config import metadata

    ladder = pd.read_parquet(asset_path("china_ladder_full"))
    ladder["origin_date"] = pd.to_datetime(ladder.origin_date)
    ladder["ref_quarter"] = pd.to_datetime(ladder.ref_quarter)

    checked = 0
    for ref, _ in PROBES:
        ref = pd.Timestamp(ref)
        rows = ladder[(ladder.ref_quarter == ref)
                      & (ladder.model == "Bridge(activity)")
                      & (ladder.origin_date >= ref.replace(month=2, day=10))
                      & (ladder.origin_date < ref.replace(month=3, day=14))]
        for _, row in rows.iterrows():
            _, info = _info_at(row.origin_date, ref)
            model = modelset.build(
                {"Bridge(activity)": metadata.MODELS["china"]["Bridge(activity)"]}
            )["Bridge(activity)"]
            try:
                got = float(model.fit(info).nowcast(info).mean)
            except Exception:
                got = float("nan")
            want = float(row.y_hat) if pd.notna(row.y_hat) else float("nan")
            assert (np.isnan(got) and np.isnan(want)) or got == pytest.approx(want, abs=1e-6), (
                f"ladder row at {row.origin_date.date()} for {ref.date()} does not "
                f"reproduce from the corrected panel: asset {want}, recomputed {got}. "
                "The frozen asset embeds a different (leaky) panel rule.")
            checked += 1
    assert checked >= 3, "probe window matched no ladder rows; widen the probes"


def test_manifest_declares_tracked_producer_and_panel_rule():
    man = json.loads((ROOT / "MANIFEST.json").read_text())["assets"]
    for name in ("china_ladder_full.parquet", "china_horizon_2012floor.parquet",
                 "china_tilt_weo.parquet"):
        meta = man[name]
        assert "pipeline/lib/china_assets.py" in meta.get("producer", ""), (
            f"{name}: producer is {meta.get('producer')!r}; the asset must be "
            "regenerated by the tracked producer, not a notebook")
        assert meta.get("panel_rule") == "january_blank_combined_feb_release", (
            f"{name}: panel rule not declared or stale")
