"""Target construction and its explicit availability limitation."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from .config import DATA_ROOT, REPO_ROOT, TARGET_RELEASE_LAG_DAYS


def target_release_date(month, *, lag_days: int = TARGET_RELEASE_LAG_DAYS) -> pd.Timestamp:
    """Conservative assumed availability date for a monthly GDP observation.

    The project has not reconstructed an INEI vintage release calendar for
    this target.  This is therefore a documented scalar assumption, copied
    from the existing Peru target configuration, not a claimed timestamp.
    """
    p = pd.Period(month, freq="M")
    return p.to_timestamp(how="end").normalize() + pd.Timedelta(days=int(lag_days))


def target_is_known(month, as_of, *, lag_days: int = TARGET_RELEASE_LAG_DAYS) -> bool:
    return target_release_date(month, lag_days=lag_days) <= pd.Timestamp(as_of).normalize()


def load_monthly_target(
    path: str | Path | None = None,
    *,
    lag_days: int = TARGET_RELEASE_LAG_DAYS,
) -> pd.DataFrame:
    """Load the locally reproducible SA monthly GDP level and log growth.

    ``monthly_sa_spec3.parquet`` is generated by the existing Peru X13
    preparation workflow.  It is a latest-revised, full-sample SA series.  It
    is suitable for a first pseudo-real-time MVP only and is labelled as such
    in every downstream result.  A future target-vintage store is required for
    genuine historical real-time evaluation.
    """
    path = Path(path or (REPO_ROOT / "input" / "peru" / "monthly_sa_spec3.parquet"))
    if not path.exists():
        raise FileNotFoundError(
            f"seasonally adjusted monthly GDP cache is missing: {path}. "
            "Build the existing Peru panel first; do not substitute a raw or "
            "interpolated series."
        )
    raw = pd.read_parquet(path)
    if "pbim" not in raw.columns:
        raise ValueError(f"{path} has no 'pbim' seasonally adjusted level")
    idx = pd.DatetimeIndex(raw.index).to_period("M").to_timestamp(how="start")
    level = pd.to_numeric(raw["pbim"], errors="coerce").set_axis(idx)
    out = pd.DataFrame({"target_month": idx, "pbi_sa_index": level.to_numpy()})
    out = out.drop_duplicates("target_month", keep="last").sort_values("target_month")
    out["pbi_mom_pct"] = 100.0 * np.log(out.pbi_sa_index).diff()
    out["target_release_date"] = [target_release_date(x, lag_days=lag_days)
                                  for x in out.target_month]
    out["target_source"] = "BCRP/INEI monthly GDP level, local X13 SA cache"
    out["target_revision_regime"] = "latest_revised_full_sample_X13"
    out["target_release_rule"] = f"assumed_period_end_plus_{int(lag_days)}d"
    return out.reset_index(drop=True)


def write_monthly_target(target: pd.DataFrame, *, data_root: str | Path = DATA_ROOT) -> Path:
    """Persist the target derived from the existing cache, never hand-edited."""
    root = Path(data_root)
    path = root / "processed" / "target_monthly.parquet"
    path.parent.mkdir(parents=True, exist_ok=True)
    target.to_parquet(path, index=False)
    return path

